### ISSUE TITLE
Configuration File？

### ISSUE THREAD

**Issue by iamxg** [aignacio/mqtt-sn-contiki_example#1]
Hi，
I want to learn MQTT-SN protocol by using your example. But I don't know how to write the configure file config.mqtt. Can you help me?
https://blog.aignacio.com/2017/06/25/6lowpan-mqtt-and-contiki-os/

Best Regards,
Xian

**Comment by aignacio** [comment]
Hello @iamxg 
When you clone this repo, you should download a zip file (mosquitto.rsmb.zip) that contains the config.mqtt
mqtt-sn-contiki_example/tools/mosquitto.rsmb/rsmb/src/config.mqtt

**Comment by iamxg** [comment]
Hi，
There is no any file in the folder “examples/tools/mosquitto.rsmb/rsmb/” after I download. I installed rsmb from https://github.com/eclipse/mosquitto.rsmb. I don't know why?
Best Regards,
Xian

**Comment by aignacio** [comment]
It's strange that you couldn't be able to download, so I'll upload here for you...
[mosquitto.rsmb.zip](https://github.com/aignacio/mqtt-sn-contiki_example/files/2604706/mosquitto.rsmb.zip)

**Comment by iamxg** [comment]
Thank you very much!
Have a good day!
I will test it. Thank you!

**Comment by iamxg** [comment]
I am so soryy! I also faced this problem. My system is also x86 architecture.
![image](https://user-images.githubusercontent.com/30093996/48854861-dd432f80-eded-11e8-957e-c5f547198463.png)

**Comment by aignacio** [comment]
So you'll need to run in a x64 architecture this broker

**Comment by syed-nadeem** [comment]
Hello 
I want to learn MQTT-SN protocol by your example. But when i open simulation file simulation_mqtt_sn.csc
It shows error 
![IMG20200209173418](https://user-images.githubusercontent.com/48100883/74102118-6fa23100-4b62-11ea-84cc-2c982b853c49.jpg)
Can you help please

**Comment by aignacio** [comment]
Please follow https://blog.aignacio.com/6lowpan-mqtt-and-contiki-os/
