### ISSUE TITLE
Error while running MQTT-SN in Contiki

### ISSUE THREAD

**Issue by vishal623** [aignacio/mqtt-sn-contiki_example#3]
Hi @aignacio

I have tried to run the MQTT-sn in Contiki. Everything works fine for me except rsmb broker.

following is the command and error that prompt.

user@instant-contiki:~/contiki/mqtt-sn-contiki/tools/mosquitto.rsmb/rsmb/src$ sudo ./broker_mqtts config.mqtt
./broker_mqtts: 1: ./broker_mqtts: Syntax error: "(" unexpected

I have also gone through the broker.c file but there is not initial bracket for that.

Regards,
Vishal

**Comment by aignacio** [comment]
The problem is that you're trying to run the broker in a machine that x86 (32-bits arch) and the source code of the broker was compiled to a x64. Pls check the first warning in the blog post about it again =)

**Comment by vishal623** [comment]
Hello sir,

I am able to resolve the error. I have downloaded the new RSMB broker from the git repository and set the config as per your config file and then after it is running. 

But now, I am getting the following message when I run the broker with the config file. 

user@instant-contiki:~/contiki/mqtt-sn-contiki/tools/mosquitto.rsmb/rsmb/src$ sudo ./broker_mqtts config.mqtt
20200321 151708.743 CWNAN9999I Really Small Message Broker
20200321 151708.743 CWNAN9998I Part of Project Mosquitto in Eclipse
(http://projects.eclipse.org/projects/technology.mosquitto)
20200321 151708.743 CWNAN0049I Configuration file name is config.mqtt
20200321 151708.743 CWNAN0053I Version 1.3.0.2, Mar 21 2020 15:13:26
20200321 151708.746 CWNAN0054I Features included: bridge MQTTS 
20200321 151708.746 CWNAN9993I Authors: Ian Craggs (icraggs@uk.ibm.com), Nicholas O'Leary
20200321 151708.747 CWNAN0075W Socket error 98 (Address already in use) in a bind for socket 3
20200321 151708.747 CWNAN0078W Cannot bind port 1883
20200321 151708.747 CWNAN0015W Cannot start listener on port 1883
20200321 151708.747 CWNAN0016I MQTT protocol stopping
20200321 151708.747 CWNAN0301I MQTT-S protocol stopping
20200321 151708.747 CWNAN0075W Socket error 88 (Socket operation on non-socket) in shutdown for socket 0
20200321 151708.747 CWNAN0044I Messages sent: 0
20200321 151708.747 CWNAN0043I Messages received: 0
20200321 151708.747 CWNAN0042I Uptime: 0 seconds
20200321 151708.747 CWNAN0055I Maximum heap use: 129104 bytes
20200321 151708.747 CWNAN0047I Broker stopped

**Comment by vishal623** [comment]
> The problem is that you're trying to run the broker in a machine that x86 (32-bits arch) and the source code of the broker was compiled to a x64. Pls check the first warning in the blog post about it again =)

Thank sir.

I will try to run it in the local machine instead of VM.

**Comment by vishal623** [comment]
Hi @aignacio 

I am able to run it on my local machine. 

I have one more question. Do you have any idea about running MQTT in Contiki? I have tried different things but didn't work for me.

**Comment by aignacio** [comment]
Hi @vishal623,
it has been a long time since I worked with contiki, when I used they still didn't have changed to contiki-ng. I remember when I tried to use MQTT (tcp ofc) was extremely slow and heavy in terms of processing for my embedded targets so that's why I gave up and write my own mqtt-sn lib, to be fully honest I don't work anymore with contiki, neither mqtt/sn nowadays, so it's hard to me to guide you anyway, I'd suggest you go over contiki-ng repo and ask directly there.

**Comment by vishal623** [comment]
Thanks sir.
